### ISSUE TITLE
Accessing gridstack instance

### ISSUE THREAD

**Issue by adamunion** [kdietrich/gridstack-angular#11]
What's the best way of accessing the gridstack instance so I can use methods such as enableMove() and enableDrag() ?

**Comment by kdietrich** [comment]
You have to use latest master for this:

    <div gridstack gridstack-handler="gridstacker">
         ...
    </div>

Then you can access gridstack:

    $scope.gridstacker = null;

**Comment by AlexanderSergan** [comment]
Works great, thanx @kdietrich!
