### ISSUE TITLE
Widgets positions not updated while removing

### ISSUE THREAD

**Issue by Winnilis** [kdietrich/gridstack-angular#13]
Hi,

Thanks for the angular version. Why isn't the position of every widget updated when one of them is removed ?
On the [demo](http://kdietrich.github.io/gridstack-angular/demo/#), if you add 2 widgets under those which exist 
![capture1](https://cloud.githubusercontent.com/assets/12530257/16117391/23c04bd8-33d2-11e6-8eb8-2cf2e27c6207.PNG)

and then remove the 2 first one, grid height is well updated but widgets stay where they are
![capture2](https://cloud.githubusercontent.com/assets/12530257/16117403/2f4b53da-33d2-11e6-8542-1bf605952772.PNG)

and I need to drag them manually or to add a new widget to force their new position.

Is there a way to force the update ?
Thanks.

**Comment by inventaethiago** [comment]
I solved this by modifying the "destroy" function to call Gridstack's batchUpdate() and commit() methods before and after removing the item, respectively.

**Comment by kdietrich** [comment]
This is a bug that got introduced in gridstack.js `v0.2.5`. We're going to fix it there. See https://github.com/troolee/gridstack.js/issues/411 for more info.

**Comment by kdietrich** [comment]
Fixed!
