### ISSUE TITLE
Two way data binding not working?

### ISSUE THREAD

**Issue by mkelso** [kdietrich/gridstack-angular#2]
Hey,

From your demo page, it appears that the two way data binding is not working. If you resize any of the objects, $scope.widgets does not update.
This is the same with my implementation of the code.
Am I doing something obviously wrong? Or how do you 'export' the finalised version?

Cheers

**Comment by kdietrich** [comment]
This started as a little side project and I didn't really need two way binding back then. I've updated the code, it is now fully supported. See [demo](http://kdietrich.github.io/gridstack-angular/demo/).
