### ISSUE TITLE
Function `make_widget` is deprecated

### ISSUE THREAD

**Issue by Tiagojdferreira** [kdietrich/gridstack-angular#5]
Using the mininified version of your library I get the following warning:

````
gridstack.js: Function `make_widget` is deprecated as of v0.2.5 and has been replaced with `makeWidget`. It will be **completely** removed in v1.0.

````

Regarding the problem with the debugger, I see that in the gridstack-angular.min.js, there is the following line:

````
 this.addItem = function(t) {
            return r ? (r.make_widget(t),
            t) : null 
        }
````

Similar for remove_widget.

**Comment by kdietrich** [comment]
Some methods were marked as deprecated in gridstack `v0.2.5`. I've already fixed that in master. :+1:

**Comment by Tiagojdferreira** [comment]
Cool, but could you make that these changes also are reflected in bower install ? If you could that would be awesome!

**Comment by kdietrich** [comment]
@Tiagojdferreira Done. https://github.com/kdietrich/gridstack-angular/releases/tag/v0.4.0
