### ISSUE TITLE
New grid with multi-row does not initialize correctly

### ISSUE THREAD

**Issue by adamunion** [kdietrich/gridstack-angular#9]
Hi,

Thanks for the angular port. I cloned the demo and tried to set #scope.widgets to include one of the default items on the second row, i.e:
`$scope.widgets = [{"x":"1","y":"1","width":"1","height":"1"},{"x":"1","y":"0","width":"3","height":"1"}];`

However when I refresh both items are on the first row. I was hoping this worked like the serialization [demo page](http://troolee.github.io/gridstack.js/demo/serialization.html).

**Comment by kdietrich** [comment]
The demo is using `gs-item-autopos="1"` and thus automatically reordering added items to save space. If you don't want this, set `gs-item-autopos` to zero.

**Comment by adamunion** [comment]
Perfect, thank you so much.
